# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\redes\Documents\DESARROLLOS\JimeCalc\calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 391)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1.setGeometry(QtCore.QRect(20, 90, 51, 41))
        self.boton1.setStyleSheet("font-size: 20px\n"
"")
        self.boton1.setObjectName("boton1")
        self.boton2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2.setGeometry(QtCore.QRect(80, 90, 51, 41))
        self.boton2.setStyleSheet("font-size: 20px\n"
"")
        self.boton2.setObjectName("boton2")
        self.boton3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3.setGeometry(QtCore.QRect(140, 90, 51, 41))
        self.boton3.setStyleSheet("font-size: 20px\n"
"")
        self.boton3.setObjectName("boton3")
        self.boton6 = QtWidgets.QPushButton(self.centralwidget)
        self.boton6.setGeometry(QtCore.QRect(140, 140, 51, 41))
        self.boton6.setStyleSheet("font-size: 20px\n"
"")
        self.boton6.setObjectName("boton6")
        self.boton4 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4.setGeometry(QtCore.QRect(20, 140, 51, 41))
        self.boton4.setStyleSheet("font-size: 20px\n"
"")
        self.boton4.setObjectName("boton4")
        self.boton5 = QtWidgets.QPushButton(self.centralwidget)
        self.boton5.setGeometry(QtCore.QRect(80, 140, 51, 41))
        self.boton5.setStyleSheet("font-size: 20px\n"
"")
        self.boton5.setObjectName("boton5")
        self.boton9 = QtWidgets.QPushButton(self.centralwidget)
        self.boton9.setGeometry(QtCore.QRect(140, 190, 51, 41))
        self.boton9.setStyleSheet("font-size: 20px\n"
"")
        self.boton9.setObjectName("boton9")
        self.boton7 = QtWidgets.QPushButton(self.centralwidget)
        self.boton7.setGeometry(QtCore.QRect(20, 190, 51, 41))
        self.boton7.setStyleSheet("font-size: 20px\n"
"")
        self.boton7.setObjectName("boton7")
        self.boton8 = QtWidgets.QPushButton(self.centralwidget)
        self.boton8.setGeometry(QtCore.QRect(80, 190, 51, 41))
        self.boton8.setStyleSheet("font-size: 20px\n"
"")
        self.boton8.setObjectName("boton8")
        self.suma = QtWidgets.QPushButton(self.centralwidget)
        self.suma.setGeometry(QtCore.QRect(220, 90, 51, 41))
        self.suma.setStyleSheet("font-size: 20px\n"
"")
        self.suma.setObjectName("suma")
        self.producto = QtWidgets.QPushButton(self.centralwidget)
        self.producto.setGeometry(QtCore.QRect(220, 190, 51, 41))
        self.producto.setStyleSheet("font-size: 20px\n"
"")
        self.producto.setObjectName("producto")
        self.resta = QtWidgets.QPushButton(self.centralwidget)
        self.resta.setGeometry(QtCore.QRect(220, 140, 51, 41))
        self.resta.setStyleSheet("font-size: 20px\n"
"")
        self.resta.setObjectName("resta")
        self.boton0 = QtWidgets.QPushButton(self.centralwidget)
        self.boton0.setGeometry(QtCore.QRect(20, 240, 51, 41))
        self.boton0.setStyleSheet("font-size: 20px\n"
"")
        self.boton0.setObjectName("boton0")
        self.igual = QtWidgets.QPushButton(self.centralwidget)
        self.igual.setGeometry(QtCore.QRect(280, 240, 111, 41))
        self.igual.setStyleSheet("font-size: 20px\n"
"")
        self.igual.setObjectName("igual")
        self.backup = QtWidgets.QLineEdit(self.centralwidget)
        self.backup.setGeometry(QtCore.QRect(20, 310, 113, 20))
        self.backup.setObjectName("backup")
        self.div = QtWidgets.QPushButton(self.centralwidget)
        self.div.setGeometry(QtCore.QRect(220, 240, 51, 41))
        self.div.setObjectName("div")
        self.raiz = QtWidgets.QPushButton(self.centralwidget)
        self.raiz.setGeometry(QtCore.QRect(340, 190, 51, 41))
        self.raiz.setObjectName("raiz")
        self.potencia = QtWidgets.QPushButton(self.centralwidget)
        self.potencia.setGeometry(QtCore.QRect(340, 140, 51, 41))
        self.potencia.setObjectName("potencia")
        self.borrarop = QtWidgets.QPushButton(self.centralwidget)
        self.borrarop.setGeometry(QtCore.QRect(340, 90, 51, 41))
        self.borrarop.setObjectName("borrarop")
        self.btdes = QtWidgets.QPushButton(self.centralwidget)
        self.btdes.setGeometry(QtCore.QRect(280, 90, 51, 41))
        self.btdes.setObjectName("btdes")
        self.coma = QtWidgets.QPushButton(self.centralwidget)
        self.coma.setGeometry(QtCore.QRect(80, 240, 51, 41))
        self.coma.setObjectName("coma")
        self.calculo = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.calculo.setGeometry(QtCore.QRect(20, 20, 371, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.calculo.setFont(font)
        self.calculo.setObjectName("calculo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton1.setText(_translate("MainWindow", "1"))
        self.boton2.setText(_translate("MainWindow", "2"))
        self.boton3.setText(_translate("MainWindow", "3"))
        self.boton6.setText(_translate("MainWindow", "6"))
        self.boton4.setText(_translate("MainWindow", "4"))
        self.boton5.setText(_translate("MainWindow", "5"))
        self.boton9.setText(_translate("MainWindow", "9"))
        self.boton7.setText(_translate("MainWindow", "7"))
        self.boton8.setText(_translate("MainWindow", "8"))
        self.suma.setText(_translate("MainWindow", "+"))
        self.producto.setText(_translate("MainWindow", "*"))
        self.resta.setText(_translate("MainWindow", "-"))
        self.boton0.setText(_translate("MainWindow", "0"))
        self.igual.setText(_translate("MainWindow", "="))
        self.div.setText(_translate("MainWindow", "÷"))
        self.raiz.setText(_translate("MainWindow", "√"))
        self.potencia.setText(_translate("MainWindow", "^"))
        self.borrarop.setText(_translate("MainWindow", "C"))
        self.btdes.setText(_translate("MainWindow", "AC"))
        self.coma.setText(_translate("MainWindow", ","))
